### ISSUE TITLE
Still getting seg-faults in the file browser

### ISSUE THREAD

**Issue by cwiede** [ifm/nexxT#20]
Additionally there is not-so optimal behaviour on slow networks. So this means that the QFileSystemModel doesn't do the job nicely, also correct sorting needed a nasty workaround. Also, on deep nested folder structures, it needs a lot of space.

Refactoring this to a FolderListView-like model with a tab-expandable text edit should be the way to go in the future.

**Comment by n-e-y-s** [comment]
Fixed with https://github.com/ifm/nexxT/commit/673a85cb5aa2613793b79b38dbaa589d1bee8f85

**Comment by cwiede** [comment]
https://github.com/ifm/nexxT/commit/673a85cb5aa2613793b79b38dbaa589d1bee8f85
